"""
In-memory conversation history management for the AI agent.

Each session (Telegram chat or web UI client) gets its own message list
stored in the format expected by the OpenAI Chat Completions API.
"""

from __future__ import annotations

from typing import Any, Dict, List


Message = Dict[str, Any]


class ConversationMemory:
    """
    Simple in-memory message store keyed by session_id.

    session_id is typically the Telegram chat_id (as a string) or a
    UUID generated by the web UI client.
    """

    def __init__(self) -> None:
        """Initialise with an empty sessions dict."""
        self._sessions: Dict[str, List[Message]] = {}

    def add_message(self, session_id: str, role: str, content: Any) -> None:
        """
        Append a plain user or assistant message to the session history.

        role must be one of: 'user', 'assistant', 'system'.
        """

        if session_id not in self._sessions:
            self._sessions[session_id] = []
        self._sessions[session_id].append({"role": role, "content": content})

    def add_assistant_tool_call(self, session_id: str, tool_calls: List[Dict[str, Any]]) -> None:
        """
        Append an assistant message that contains tool_calls (no content text).

        This is required by the OpenAI API to maintain a valid message sequence
        when the assistant decided to invoke one or more tools.
        """

        if session_id not in self._sessions:
            self._sessions[session_id] = []
        self._sessions[session_id].append(
            {
                "role": "assistant",
                "content": None,
                "tool_calls": tool_calls,
            }
        )

    def add_tool_result(self, session_id: str, tool_call_id: str, content: str) -> None:
        """
        Append a tool result message in the correct OpenAI format.

        tool_call_id must match the id of the corresponding tool_call in the
        preceding assistant message so the API can correlate them.
        """

        if session_id not in self._sessions:
            self._sessions[session_id] = []
        self._sessions[session_id].append(
            {
                "role": "tool",
                "tool_call_id": tool_call_id,
                "content": content,
            }
        )

    def get_history(self, session_id: str) -> List[Message]:
        """
        Return a copy of the full message history for the given session.
        """

        return list(self._sessions.get(session_id, []))

    def clear_history(self, session_id: str) -> None:
        """
        Remove all messages for the given session.
        """

        self._sessions.pop(session_id, None)


# Global singleton used by both the agent and the Telegram bot.
memory = ConversationMemory()
