"""
In-memory conversation history and user context management for the AI agent.

Each session (Telegram chat or web UI client) gets its own message list
stored in the format expected by the OpenAI Chat Completions API, plus
an optional user context dict that tracks who is logged in.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional


Message = Dict[str, Any]


class ConversationMemory:
    """
    Simple in-memory message store keyed by session_id.

    session_id is typically the Telegram chat_id (as a string) or a
    UUID generated by the web UI client.
    """

    def __init__(self) -> None:
        """Initialise with empty sessions and user context dicts."""
        self._sessions: Dict[str, List[Message]] = {}
        self._user_context: Dict[str, Dict[str, Any]] = {}

    # ── Message management ─────────────────────────────────────────────────

    def add_message(self, session_id: str, role: str, content: Any) -> None:
        """
        Append a plain user or assistant message to the session history.

        role must be one of: 'user', 'assistant', 'system'.
        """

        if session_id not in self._sessions:
            self._sessions[session_id] = []
        self._sessions[session_id].append({"role": role, "content": content})

    def add_assistant_tool_call(self, session_id: str, tool_calls: List[Dict[str, Any]]) -> None:
        """
        Append an assistant message that contains tool_calls (no content text).

        This is required by the OpenAI API to maintain a valid message sequence
        when the assistant decided to invoke one or more tools.
        """

        if session_id not in self._sessions:
            self._sessions[session_id] = []
        self._sessions[session_id].append(
            {
                "role": "assistant",
                "content": None,
                "tool_calls": tool_calls,
            }
        )

    def add_tool_result(self, session_id: str, tool_call_id: str, content: str) -> None:
        """
        Append a tool result message in the correct OpenAI format.

        tool_call_id must match the id of the corresponding tool_call in the
        preceding assistant message so the API can correlate them.
        """

        if session_id not in self._sessions:
            self._sessions[session_id] = []
        self._sessions[session_id].append(
            {
                "role": "tool",
                "tool_call_id": tool_call_id,
                "content": content,
            }
        )

    def get_history(self, session_id: str) -> List[Message]:
        """
        Return a copy of the full message history for the given session.
        """

        return list(self._sessions.get(session_id, []))

    def clear_messages(self, session_id: str) -> None:
        """
        Remove message history only, keeping user context intact.
        """

        self._sessions.pop(session_id, None)

    def clear_all(self, session_id: str) -> None:
        """
        Remove everything for the session (messages + user context).
        """

        self._sessions.pop(session_id, None)
        self._user_context.pop(session_id, None)

    # ── User context management ────────────────────────────────────────────

    def set_user_context(self, session_id: str, username: str, club_name: Optional[str], role: str) -> None:
        """Bind a validated user to this session."""

        self._user_context[session_id] = {
            "username": username,
            "club_name": club_name,
            "role": role,
        }

    def get_user_context(self, session_id: str) -> Optional[Dict[str, Any]]:
        """Return the user context for this session, or None if not logged in."""

        return self._user_context.get(session_id)

    def is_logged_in(self, session_id: str) -> bool:
        """Check if the session has a bound user."""

        return session_id in self._user_context


# Global singleton used by both the agent and the Telegram bot.
memory = ConversationMemory()
